"""
src/data/synthetic/__init__.py

Synthetic data engine package for HOPIUM_sih26170.
All data generated by this package is synthetic and must never be
represented as real ISRO or industry component data.
"""
