"""
src/data/synthetic/generator.py

Main SyntheticDataEngine for the HOPIUM_sih26170 project (Phase 1).

Generates reproducible synthetic burn-in trajectory datasets following the
approved Phase 1 Specification (Revision 3) and docs/DATA_CONTRACT.md.

IMPORTANT:
  - All generated data is SYNTHETIC. It is NOT real ISRO or industry data.
  - synthetic_spec_min / synthetic_spec_max are configurable synthetic reference
    limits for testing and demonstration. They are NOT real datasheet limits.
  - Cross-parameter correlation values are SYNTHETIC MODELLING ASSUMPTIONS.

Production feature boundary (enforced architecturally):
  Module B production inputs: value_0h, value_24h ONLY.
  value_96h and value_168h are stored for ground truth; they must NEVER
  enter production inference feature matrices.

Generator invariants:
  1. population_anomaly is generated by lot-relative statistical displacement.
     It does NOT depend on synthetic reference-limit breach.
  2. reference_limit_breach is generated by direct absolute value injection.
     It may occur without population_anomaly.
  3. A component may have neither, either, or both attributes.
"""

import math
import random
from typing import Dict, List, Optional, Tuple

import numpy as np

from .correlation import (
    build_cholesky_factor,
    sample_correlated_baselines,
    validate_correlation_matrix,
)
from .schema import (
    ComponentGroundTruth,
    DatasetMetadata,
    ParameterGroundTruth,
    TrajectoryRow,
)
from .trajectories import EARLY_DETECTABILITY_SCALE, evaluate_trajectory


def _weighted_choice(py_rng: random.Random, choices: list, weights: list):
    """
    Select one item from choices according to normalized weights.
    stdlib random.Random.choice() does not accept a p= keyword;
    this helper provides equivalent weighted selection.
    """
    assert len(choices) == len(weights)
    total = sum(weights)
    r = py_rng.random() * total
    cumulative = 0.0
    for item, w in zip(choices, weights):
        cumulative += w
        if r < cumulative:
            return item
    return choices[-1]


# ---------------------------------------------------------------------------
# Parameter name and unit constants (from DATA_CONTRACT.md)
# ---------------------------------------------------------------------------
PARAMETERS = ["Iddq", "leakage_current", "propagation_delay"]
PARAM_IDX = {p: i for i, p in enumerate(PARAMETERS)}
TIMEPOINTS = [0.0, 24.0, 96.0, 168.0]


class SyntheticDataEngine:
    """
    Reproducible synthetic burn-in dataset generator.

    Usage
    -----
    engine = SyntheticDataEngine(config=cfg, seed=42)
    rows, comp_gt, param_gt = engine.generate(
        num_lots=20, components_per_lot=100
    )
    """

    def __init__(self, config: dict, seed: int):
        """
        Initialise the generator with a configuration dict and master seed.

        Parameters
        ----------
        config : dict
            Parsed contents of synthetic_generator_config key from YAML.
        seed : int
            Master random seed. Deterministic regeneration is guaranteed when
            (seed, config, generator_version) are identical.
        """
        self.config = config
        self.seed = seed
        self.generator_version = config["generator_version"]

        # Build per-parameter lookup
        self.param_cfg: Dict[str, dict] = config["parameters"]

        # Validate and prepare correlation machinery
        R_raw = config["cross_parameter_correlation"]["R_matrix"]
        self.R = np.array(R_raw, dtype=float)
        validate_correlation_matrix(self.R)  # Raises ValueError if invalid
        self.L = build_cholesky_factor(self.R)  # Cholesky factor of R

        # Per-parameter global sigmas (for D in Sigma = D R D)
        self.sigmas = [self.param_cfg[p]["global_sigma"] for p in PARAMETERS]
        self.means = [self.param_cfg[p]["global_mean"] for p in PARAMETERS]

        # Prevalence / severity config
        self.prevalence = config["class_prevalence"]
        self.severity_scale = config["severity_scale"]
        self.latent_cfg = config["latent_degradation"]
        self.variance_cfg = config["variance_structure"]

    # -----------------------------------------------------------------------
    # Public entry point
    # -----------------------------------------------------------------------

    def generate(
        self,
        num_lots: int,
        components_per_lot: int,
    ) -> Tuple[List[TrajectoryRow], List[ComponentGroundTruth], List[ParameterGroundTruth]]:
        """
        Generate a complete dataset with ground truth.

        Parameters
        ----------
        num_lots : int
        components_per_lot : int

        Returns
        -------
        rows : list of TrajectoryRow
            One row per (component, parameter) pair.
        component_gt : list of ComponentGroundTruth
        parameter_gt : list of ParameterGroundTruth
        """
        # Seed all RNGs from master seed to ensure full determinism
        rng = np.random.default_rng(self.seed)
        py_rng = random.Random(self.seed)

        rows: List[TrajectoryRow] = []
        component_gt: List[ComponentGroundTruth] = []
        parameter_gt: List[ParameterGroundTruth] = []

        for lot_idx in range(num_lots):
            lot_id = f"LOT_{lot_idx + 1:03d}"

            # ---- Lot-level center shift (per parameter, correlated) --------
            lot_sigma_scale = self.variance_cfg["sigma_lot_ratio"]
            lot_means_shift = self._sample_lot_shift(rng, lot_sigma_scale)

            # ---- Component baselines for this lot --------------------------
            component_baselines = self._sample_component_baselines(
                rng=rng,
                n=components_per_lot,
                lot_shift=lot_means_shift,
                comp_sigma_scale=self.variance_cfg["sigma_comp_ratio"],
            )

            # ---- Intra-lot sigma for population anomaly displacement --------
            intra_lot_sigma = np.array(self.sigmas) * self.variance_cfg["sigma_comp_ratio"]

            for comp_idx in range(components_per_lot):
                comp_id = f"{lot_id}_CMP_{comp_idx + 1:04d}"
                baseline = component_baselines[comp_idx]  # shape (n_params,)

                # ---- Assign behavioral state --------------------------------
                behavioral_state, early_detectability = self._assign_behavioral_state(py_rng)

                # ---- Assign anomaly attributes (independent of behavioral state)
                is_pop_anomaly = py_rng.random() < self.prevalence["population_anomaly_attr_pct"]
                is_ref_breach = py_rng.random() < self.prevalence["reference_limit_breach_attr_pct"]

                # ---- Population anomaly displacement (independent mechanism) -
                # Generator Invariant: population_anomaly shift does NOT use
                # synthetic_spec limits; it uses lot-relative sigma displacement.
                pop_anomaly_severity = None
                pop_displacement = np.zeros(len(PARAMETERS))
                if is_pop_anomaly:
                    sev_keys = list(self.severity_scale.keys())
                    pop_anomaly_severity = _weighted_choice(
                        py_rng, sev_keys, [0.30, 0.40, 0.20, 0.10]
                    )
                    k = self.severity_scale[pop_anomaly_severity]
                    # Apply displacement to one or more parameters
                    n_affected = py_rng.randint(1, len(PARAMETERS))  # stdlib: inclusive both ends
                    affected_params = py_rng.sample(range(len(PARAMETERS)), n_affected)
                    direction = py_rng.choice([-1.0, 1.0])
                    for pi in affected_params:
                        pop_displacement[pi] = direction * k * intra_lot_sigma[pi]

                # ---- Reference-limit breach injection (independent mechanism) -
                # Generator Invariant: reference_limit_breach does NOT require
                # population_anomaly; it injects values outside synthetic limits.
                ref_breach_severity = None
                ref_breach_override: Dict[int, float] = {}
                if is_ref_breach:
                    sev_keys = list(self.severity_scale.keys())
                    ref_breach_severity = _weighted_choice(
                        py_rng, sev_keys, [0.20, 0.30, 0.30, 0.20]
                    )
                    k = self.severity_scale[ref_breach_severity]
                    # Breach one randomly chosen parameter
                    pi = py_rng.randrange(len(PARAMETERS))
                    pname = PARAMETERS[pi]
                    spec_max = self.param_cfg[pname]["synthetic_spec_max"]
                    spec_min = self.param_cfg[pname]["synthetic_spec_min"]
                    span = (spec_max - spec_min)
                    # Push value above spec_max by a fraction of span * severity
                    ref_breach_override[pi] = spec_max + (k * 0.05 * span)


                # ---- Severity for ground truth summary ----------------------
                active_attrs = []
                if is_pop_anomaly:
                    active_attrs.append("population_anomaly")
                if is_ref_breach:
                    active_attrs.append("reference_limit_breach")

                worst_severity = None
                if is_pop_anomaly or is_ref_breach:
                    sev_rank = list(self.severity_scale.keys())
                    candidates = []
                    if pop_anomaly_severity:
                        candidates.append(pop_anomaly_severity)
                    if ref_breach_severity:
                        candidates.append(ref_breach_severity)
                    worst_severity = max(candidates, key=lambda s: sev_rank.index(s))

                # ---- Store component ground truth ---------------------------
                component_gt.append(ComponentGroundTruth(
                    component_id=comp_id,
                    lot_id=lot_id,
                    behavioral_state=behavioral_state,
                    is_latent_degrader=(behavioral_state == "latent_degradation"),
                    early_detectability=early_detectability,
                    is_population_anomaly=is_pop_anomaly,
                    is_reference_limit_breach=is_ref_breach,
                    anomaly_attributes=active_attrs,
                    severity_level=worst_severity,
                ))

                # ---- Generate trajectory for each parameter -----------------
                for pi, pname in enumerate(PARAMETERS):
                    pcfg = self.param_cfg[pname]

                    # Effective baseline for this component/parameter
                    v0_nominal = baseline[pi] + pop_displacement[pi]

                    # Reference-limit breach overrides the 0h value if flagged
                    if pi in ref_breach_override:
                        v0_nominal = ref_breach_override[pi]

                    # Clamp to non-negative for current/delay parameters
                    v0_nominal = max(v0_nominal, 0.0)

                    # Select trajectory family
                    traj_family = pcfg["trajectory_family"][behavioral_state]

                    # Generate trajectory values at each timepoint
                    tvals = {}
                    for t in TIMEPOINTS:
                        drift = evaluate_trajectory(
                            family=traj_family,
                            t=t,
                            param_cfg=pcfg,
                            early_detectability=early_detectability,
                        )
                        noise = rng.normal(0.0, pcfg["nominal_noise_std"])
                        tvals[t] = max(v0_nominal + drift + noise, 0.0)

                    # ---- Build TrajectoryRow (production feature boundary) --
                    # value_96h and value_168h are stored here for ground truth
                    # evaluation only. They must NEVER enter production feature
                    # matrices (enforced by test_module_b_features.py in Phase 3).
                    rows.append(TrajectoryRow(
                        lot_id=lot_id,
                        component_id=comp_id,
                        parameter_name=pname,
                        unit=pcfg["unit"],
                        value_0h=tvals[0.0],
                        value_24h=tvals[24.0],
                        value_96h=tvals[96.0],
                        value_168h=tvals[168.0],
                        synthetic_spec_min=pcfg["synthetic_spec_min"],
                        synthetic_spec_max=pcfg["synthetic_spec_max"],
                    ))

                    # ---- Parameter-level ground truth ----------------------
                    true_168h = tvals[168.0]
                    true_drift = true_168h - tvals[0.0]
                    is_param_anomalous = is_pop_anomaly or is_ref_breach
                    param_sev = (
                        worst_severity if is_param_anomalous else None
                    )
                    parameter_gt.append(ParameterGroundTruth(
                        component_id=comp_id,
                        parameter_name=pname,
                        true_value_168h=true_168h,
                        true_drift_168h=true_drift,
                        is_parameter_anomalous=is_param_anomalous,
                        parameter_anomaly_severity=param_sev,
                    ))

        return rows, component_gt, parameter_gt

    # -----------------------------------------------------------------------
    # Demonstration dataset: controlled cases A-D
    # -----------------------------------------------------------------------

    def generate_demo(
        self,
        num_lots: int,
        components_per_lot: int,
    ) -> Tuple[List[TrajectoryRow], List[ComponentGroundTruth], List[ParameterGroundTruth]]:
        """
        Generate a controlled demonstration dataset containing guaranteed
        instances of Cases A, B, C, and D as specified:

          A. DEMO_NOMINAL         — nominal, within synthetic limits, normal in lot
          B. DEMO_POP_ANOMALY     — within synthetic limits but population-anomalous
          C. DEMO_BREACH_AND_POP  — reference-limit breach AND population-anomalous
          D. DEMO_LATENT          — within limits at 0h/24h; latent degradation later

        Cases A-D are placed in LOT_001 at component positions 1-4.
        The remainder of the dataset is generated normally.

        Parameters
        ----------
        num_lots : int
        components_per_lot : int
        """
        rng = np.random.default_rng(self.seed)
        py_rng = random.Random(self.seed)

        rows: List[TrajectoryRow] = []
        component_gt: List[ComponentGroundTruth] = []
        parameter_gt: List[ParameterGroundTruth] = []

        for lot_idx in range(num_lots):
            lot_id = f"LOT_{lot_idx + 1:03d}"
            lot_sigma_scale = self.variance_cfg["sigma_lot_ratio"]
            lot_means_shift = self._sample_lot_shift(rng, lot_sigma_scale)

            component_baselines = self._sample_component_baselines(
                rng=rng,
                n=components_per_lot,
                lot_shift=lot_means_shift,
                comp_sigma_scale=self.variance_cfg["sigma_comp_ratio"],
            )
            intra_lot_sigma = np.array(self.sigmas) * self.variance_cfg["sigma_comp_ratio"]

            for comp_idx in range(components_per_lot):
                comp_id = f"{lot_id}_CMP_{comp_idx + 1:04d}"
                baseline = component_baselines[comp_idx]

                # ---- Inject controlled demo cases in LOT_001 pos 1-4 ------
                if lot_idx == 0 and comp_idx < 4:
                    demo_case = comp_idx  # 0=A, 1=B, 2=C, 3=D
                    r, cgt, pgt = self._generate_demo_case(
                        case=demo_case,
                        lot_id=lot_id,
                        comp_id=comp_id,
                        baseline=baseline,
                        intra_lot_sigma=intra_lot_sigma,
                        rng=rng,
                    )
                    rows.extend(r)
                    component_gt.append(cgt)
                    parameter_gt.extend(pgt)
                    continue

                # ---- Normal generation for remaining components -------------
                behavioral_state, early_detectability = self._assign_behavioral_state(py_rng)
                is_pop_anomaly = py_rng.random() < self.prevalence["population_anomaly_attr_pct"]
                is_ref_breach = py_rng.random() < self.prevalence["reference_limit_breach_attr_pct"]

                pop_displacement = np.zeros(len(PARAMETERS))
                pop_anomaly_severity = None
                if is_pop_anomaly:
                    pop_anomaly_severity = py_rng.choice(list(self.severity_scale.keys()))
                    k = self.severity_scale[pop_anomaly_severity]
                    pi = py_rng.randrange(len(PARAMETERS))
                    direction = py_rng.choice([-1.0, 1.0])
                    pop_displacement[pi] = direction * k * intra_lot_sigma[pi]

                ref_breach_severity = None
                ref_breach_override: Dict[int, float] = {}
                if is_ref_breach:
                    ref_breach_severity = py_rng.choice(list(self.severity_scale.keys()))
                    k = self.severity_scale[ref_breach_severity]
                    pi = py_rng.randrange(len(PARAMETERS))
                    pname = PARAMETERS[pi]
                    spec_max = self.param_cfg[pname]["synthetic_spec_max"]
                    spec_min = self.param_cfg[pname]["synthetic_spec_min"]
                    span = spec_max - spec_min
                    ref_breach_override[pi] = spec_max + (k * 0.05 * span)


                active_attrs = []
                if is_pop_anomaly:
                    active_attrs.append("population_anomaly")
                if is_ref_breach:
                    active_attrs.append("reference_limit_breach")

                sev_rank = list(self.severity_scale.keys())
                worst_severity = None
                if is_pop_anomaly or is_ref_breach:
                    candidates = []
                    if pop_anomaly_severity:
                        candidates.append(pop_anomaly_severity)
                    if ref_breach_severity:
                        candidates.append(ref_breach_severity)
                    worst_severity = max(candidates, key=lambda s: sev_rank.index(s))

                component_gt.append(ComponentGroundTruth(
                    component_id=comp_id,
                    lot_id=lot_id,
                    behavioral_state=behavioral_state,
                    is_latent_degrader=(behavioral_state == "latent_degradation"),
                    early_detectability=early_detectability,
                    is_population_anomaly=is_pop_anomaly,
                    is_reference_limit_breach=is_ref_breach,
                    anomaly_attributes=active_attrs,
                    severity_level=worst_severity,
                ))

                for pi, pname in enumerate(PARAMETERS):
                    pcfg = self.param_cfg[pname]
                    v0_nominal = baseline[pi] + pop_displacement[pi]
                    if pi in ref_breach_override:
                        v0_nominal = ref_breach_override[pi]
                    v0_nominal = max(v0_nominal, 0.0)
                    traj_family = pcfg["trajectory_family"][behavioral_state]
                    tvals = {}
                    for t in TIMEPOINTS:
                        drift = evaluate_trajectory(
                            family=traj_family,
                            t=t,
                            param_cfg=pcfg,
                            early_detectability=early_detectability,
                        )
                        noise = rng.normal(0.0, pcfg["nominal_noise_std"])
                        tvals[t] = max(v0_nominal + drift + noise, 0.0)

                    rows.append(TrajectoryRow(
                        lot_id=lot_id,
                        component_id=comp_id,
                        parameter_name=pname,
                        unit=pcfg["unit"],
                        value_0h=tvals[0.0],
                        value_24h=tvals[24.0],
                        value_96h=tvals[96.0],
                        value_168h=tvals[168.0],
                        synthetic_spec_min=pcfg["synthetic_spec_min"],
                        synthetic_spec_max=pcfg["synthetic_spec_max"],
                    ))

                    is_param_anomalous = is_pop_anomaly or is_ref_breach
                    parameter_gt.append(ParameterGroundTruth(
                        component_id=comp_id,
                        parameter_name=pname,
                        true_value_168h=tvals[168.0],
                        true_drift_168h=tvals[168.0] - tvals[0.0],
                        is_parameter_anomalous=is_param_anomalous,
                        parameter_anomaly_severity=worst_severity if is_param_anomalous else None,
                    ))

        return rows, component_gt, parameter_gt

    # -----------------------------------------------------------------------
    # Private helpers
    # -----------------------------------------------------------------------

    def _assign_behavioral_state(
        self, py_rng: random.Random
    ) -> Tuple[str, Optional[str]]:
        """Randomly assign a behavioral state and (if latent) early_detectability."""
        if py_rng.random() < self.prevalence["latent_degradation_pct"]:
            state = "latent_degradation"
            # Sample early_detectability from configured distribution
            ld_dist = self.latent_cfg["early_detectability_distribution"]
            choices = list(ld_dist.keys())
            probs = list(ld_dist.values())
            r = py_rng.random()
            cumulative = 0.0
            ed = choices[-1]
            for c, p in zip(choices, probs):
                cumulative += p
                if r < cumulative:
                    ed = c
                    break
            return state, ed
        return "nominal", None

    def _sample_lot_shift(
        self, rng: np.random.Generator, sigma_scale: float
    ) -> np.ndarray:
        """
        Sample lot-level center shift for all parameters jointly using the
        correlation structure. Lot shift sigma = sigma_scale * global_sigma.
        """
        lot_sigmas = [s * sigma_scale for s in self.sigmas]
        shifts = sample_correlated_baselines(
            n_samples=1,
            means=[0.0, 0.0, 0.0],
            sigmas=lot_sigmas,
            L=self.L,
            rng=rng,
        )
        return shifts[0]  # shape (n_params,)

    def _sample_component_baselines(
        self,
        rng: np.random.Generator,
        n: int,
        lot_shift: np.ndarray,
        comp_sigma_scale: float,
    ) -> np.ndarray:
        """
        Sample n component baselines at 0h for this lot using correlated
        intra-lot variation around (global_mean + lot_shift).
        """
        comp_sigmas = [s * comp_sigma_scale for s in self.sigmas]
        comp_means = [m + ls for m, ls in zip(self.means, lot_shift)]
        baselines = sample_correlated_baselines(
            n_samples=n,
            means=comp_means,
            sigmas=comp_sigmas,
            L=self.L,
            rng=rng,
        )
        return baselines  # shape (n, n_params)

    def _generate_demo_case(
        self,
        case: int,
        lot_id: str,
        comp_id: str,
        baseline: np.ndarray,
        intra_lot_sigma: np.ndarray,
        rng: np.random.Generator,
    ) -> Tuple[List[TrajectoryRow], ComponentGroundTruth, List[ParameterGroundTruth]]:
        """
        Generate a specific demonstration case (0=A, 1=B, 2=C, 3=D).

        Case A — DEMO_NOMINAL:
            nominal behavioral state, no anomaly attributes.
        Case B — DEMO_POP_ANOMALY:
            nominal behavioral state, population_anomaly, within synthetic limits.
        Case C — DEMO_BREACH_AND_POP:
            nominal behavioral state, both population_anomaly AND reference_limit_breach.
        Case D — DEMO_LATENT:
            latent_degradation with "hidden" early detectability, no anomaly attributes.
        """
        CASE_LABELS = [
            "DEMO_NOMINAL",
            "DEMO_POP_ANOMALY",
            "DEMO_BREACH_AND_POP",
            "DEMO_LATENT",
        ]

        behavioral_state = "nominal"
        early_detectability = None
        is_pop_anomaly = False
        is_ref_breach = False
        pop_displacement = np.zeros(len(PARAMETERS))
        ref_breach_override: Dict[int, float] = {}
        anomaly_attrs = []
        severity = None

        if case == 0:
            # A — purely nominal
            pass

        elif case == 1:
            # B — population anomaly only; MUST remain within synthetic limits
            is_pop_anomaly = True
            severity = "strong"
            k = self.severity_scale[severity]
            # Displace Iddq (index 0) upward — still within its spec range
            pop_displacement[0] = k * intra_lot_sigma[0]
            anomaly_attrs = ["population_anomaly"]

        elif case == 2:
            # C — both population anomaly and reference limit breach
            is_pop_anomaly = True
            is_ref_breach = True
            severity = "severe"
            k_pop = self.severity_scale["strong"]
            pop_displacement[0] = k_pop * intra_lot_sigma[0]
            # Also push Iddq above synthetic_spec_max
            pname = "Iddq"
            spec_max = self.param_cfg[pname]["synthetic_spec_max"]
            spec_min = self.param_cfg[pname]["synthetic_spec_min"]
            ref_breach_override[0] = spec_max + 0.20 * (spec_max - spec_min)
            anomaly_attrs = ["population_anomaly", "reference_limit_breach"]

        elif case == 3:
            # D — latent degradation; hidden at 0h/24h; large drift by 168h
            behavioral_state = "latent_degradation"
            early_detectability = "hidden"

        cgt = ComponentGroundTruth(
            component_id=comp_id,
            lot_id=lot_id,
            behavioral_state=behavioral_state,
            is_latent_degrader=(behavioral_state == "latent_degradation"),
            early_detectability=early_detectability,
            is_population_anomaly=is_pop_anomaly,
            is_reference_limit_breach=is_ref_breach,
            anomaly_attributes=anomaly_attrs,
            severity_level=severity,
        )

        rows: List[TrajectoryRow] = []
        pgts: List[ParameterGroundTruth] = []

        for pi, pname in enumerate(PARAMETERS):
            pcfg = self.param_cfg[pname]

            v0_nominal = baseline[pi] + pop_displacement[pi]
            if pi in ref_breach_override:
                v0_nominal = ref_breach_override[pi]
            v0_nominal = max(v0_nominal, 0.0)

            traj_family = pcfg["trajectory_family"][behavioral_state]
            tvals = {}
            for t in TIMEPOINTS:
                drift = evaluate_trajectory(
                    family=traj_family,
                    t=t,
                    param_cfg=pcfg,
                    early_detectability=early_detectability,
                )
                noise = rng.normal(0.0, pcfg["nominal_noise_std"])
                tvals[t] = max(v0_nominal + drift + noise, 0.0)

            rows.append(TrajectoryRow(
                lot_id=lot_id,
                component_id=comp_id,
                parameter_name=pname,
                unit=pcfg["unit"],
                value_0h=tvals[0.0],
                value_24h=tvals[24.0],
                value_96h=tvals[96.0],
                value_168h=tvals[168.0],
                synthetic_spec_min=pcfg["synthetic_spec_min"],
                synthetic_spec_max=pcfg["synthetic_spec_max"],
            ))
            pgts.append(ParameterGroundTruth(
                component_id=comp_id,
                parameter_name=pname,
                true_value_168h=tvals[168.0],
                true_drift_168h=tvals[168.0] - tvals[0.0],
                is_parameter_anomalous=is_pop_anomaly or is_ref_breach,
                parameter_anomaly_severity=severity,
            ))

        return rows, cgt, pgts
